baseURL = 'https://aydanmacgregor.github.io/blog/'
languageCode = 'en-us'
title = '0xAydan'
theme = 're-terminal'

[params.Logo]
  logoText = "0xAydan"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CTF"
url = "/picoCtf/"
weight = 2

[[menu.main]]
name = "Homelab"
url = "/homelab/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4