name: Build Site

on: # Every push onto the main branch I want this workflow to be triggered
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Repo # First checkout the updated posts from the repo
        uses: actions/checkout@v3
        with:
          submodules: true # Loads the theme
          fetch-depth: 0

      - name: Setup Hugo # Setups hugo to run
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.152.2"
          extended: true

      - name: Build # Build the site
        run: hugo --minify

      - name: Deploy # Deploy our changes to GH pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public